name: Bug Report
description: Report a bug in ProSSHMac
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the details below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Open ProSSHMac
        2. Navigate to '...'
        3. Click on '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened.
    validations:
      required: true

  - type: dropdown
    id: macos-version
    attributes:
      label: macOS Version
      options:
        - macOS 26.0 (Tahoe)
        - macOS 26.1+
        - Other (specify in description)
    validations:
      required: true

  - type: dropdown
    id: hardware
    attributes:
      label: Hardware
      options:
        - Apple Silicon (M1/M2/M3/M4/M5)
        - Intel
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Affected Area
      description: Which part of the app is affected?
      multiple: true
      options:
        - Terminal / Rendering
        - SSH Connection
        - Key Management (KeyForge)
        - Certificate Authority
        - Port Forwarding
        - SFTP Transfers
        - Settings
        - UI / Navigation
        - Other

  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
      description: Add any relevant logs, error messages, or screenshots.

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context about the problem.
